#! /bin/sh

sxhkd -m 1 &

bspc monitor 0x00400002 -d I II III IV V
bspc monitor 0x00400004 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           12

bspc config normal_border_color  '#282828'
bspc config active_border_color  '#282828'
bspc config focused_border_color '#d3869b'

bspc config split_ratio          0.52

bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a Zathura state=tiled

# Start terminal
st
bspc desktop -l monocle
