#! /bin/sh

# Autostart
sxhkd -m 1 &
picom &

# Set background color
# For some reason bspwm doesn't like this to happen before it starts
hsetroot -solid '#608577' # Workaround for picom

st & # Start terminal


bspc monitor 0x00400002 -d I II III IV V
bspc monitor 0x00400004 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           12

bspc config normal_border_color  '#608577'
bspc config active_border_color  '#608577'
bspc config focused_border_color '#d3869b'

bspc config split_ratio          0.52

bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
